return {
    filetypes = {
        "c",
        "css",
        "gitcommit",
        "go",
        "haskell",
        "html",
        "java",
        "javascript",
        "javascriptreact",
        "lua",
        "markdown",
        "php",
        "python",
        "ruby",
        "rust",
        "swift",
        "toml",
        "text",
        "typescript",
        "typescriptreact",
        "zig",
        "typst",
    },
    init_options = {
        diagnosticSeverity = "hint",
        checkWhileTyping = true,
    },
}
