# Kitty terminal configuration

allow_remote_control yes
include ~/.cache/theme/kitty_colors.conf

# Font settings
font_family      FiraCode Nerd Font
font_size        14

# Window settings
enable_audio_bell       false
hide_window_decorations true
disable_ligatures       false
remember_window_size    false
initial_window_width    1920
initial_window_height   1080
window_padding_width    8
map ctrl+shift+enter launch --cwd=current
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+h previous_tab
map ctrl+shift+l next_tab
map ctrl+alt+t set_tab_title

# Cursor settings
cursor_shape            beam
cursor_beam_thickness   1.4

# Mouse settings
mouse_hide_wait         3.0
detect_url              true

# Performance settings
repaint_delay           10
input_delay             3
sync_to_monitor         true

# Tab bar
tab_bar_style           powerline

# Background opacity
background_opacity      0.75
background_blur 1
