hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })
hl.curve("overshoot",      { type = "bezier", points = { {0.5, 0.9}, {0.1, 1.1}     } })

hl.curve("easy",           { type = "spring", mass = 1, stiffness = 500, dampening = 35 })
hl.curve("rubber",         { type = "spring", mass = 1, stiffness = 200,  dampening = 15 })

hl.curve("default",        { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05} } })
hl.curve("bounce",         { type = "bezier", points = { {0.4,  0.9}, {0.6, 1.0}  } })
hl.curve("snappyReturn",   { type = "bezier", points = { {0.4,  0.9}, {0.6, 1.0}  } })

hl.animation({ leaf = "global",              enabled = true, speed = 3,   bezier = "quick"                 })
hl.animation({ leaf = "windows",             enabled = true, speed = 3,   spring = "easy",  style = "slide" })
hl.animation({ leaf = "windowsIn",           enabled = true, speed = 2.5, bezier = "snappyReturn", style = "slidevert right" })
hl.animation({ leaf = "windowsOut",          enabled = true, speed = 2.5, bezier = "snappyReturn", style = "slide" })
hl.animation({ leaf = "windowsMove",         enabled = true, speed = 3,   bezier = "bounce",       style = "slide" })
hl.animation({ leaf = "fadeIn",              enabled = true, speed = 5,   bezier = "default" })
hl.animation({ leaf = "fadeOut",             enabled = true, speed = 5,   bezier = "default" })
hl.animation({ leaf = "fadeSwitch",          enabled = true, speed = 5,   bezier = "default" })
hl.animation({ leaf = "workspaces",          enabled = true, speed = 5,   bezier = "quick", style = "slide" })
hl.animation({ leaf = "specialWorkspaceIn",  enabled = true, speed = 2,   bezier = "quick", style = "slide top"})
hl.animation({ leaf = "specialWorkspaceOut", enabled = true, speed = 2,   bezier = "quick", style = "slide bottom"})
hl.animation({ leaf = "layers",              enabled = true, speed = 1,   bezier = "bounce",  style = "slide" })
hl.animation({ leaf = "layersOut",           enabled = true, speed = 0.5, bezier = "default" })
hl.animation({ leaf = "borderangle",         enabled = true, speed = 30,  bezier = "linear",   style = "loop" })
