# ----------------------------------------------------- 
# ▄▀█ █ █ ▀█▀ █▀█ █▀ ▀█▀ ▄▀█ █▀▄ ▀█▀ 
# █▀█ █▄█  █  █▄█ ▄█  █  █▀█ █▀▄  █  
# ----------------------------------------------------- 

# System services
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME QT_STYLE_OVERRIDE
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME QT_STYLE_OVERRIDE
exec-once = systemctl --user start hyprpolkitagent
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = ~/.local/bin/nyx-theme sync
exec-once = QT_QPA_PLATFORMTHEME=gtk3 qs -c noctalia-shell

# Wayland utilities
# exec-once = hypridle
exec-once = hyprpaper

# Theme sync (apply correct theme based on time of day)
exec-once = $HOME/.local/bin/nyx-theme sync

# User applications
exec-once = syncthing --no-browser

# GTK & cursor theme
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface icon-theme 'Adwaita'
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'volantes-cursors'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 34
exec-once = hyprctl setcursor volantes_cursors 34
