-- ----------------------------------------------------- 
-- ▄▀  ██▀ █▄ █ ██▀ █▀▄ ▄▀█ █  
-- ▀▄█ ██▄ █ ▀█ ██▄ █▀▄ █▀█ █▄▄
-- ----------------------------------------------------- 

local colors = require("modules.fallback_colors")

hl.config({
    general = {
        gaps_in = 0,
        gaps_out = 4,
        border_size = 2,
        col = {
            active_border = colors.active_border,
            inactive_border = colors.inactive_border,
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
    },
    -- Noctalia v5 overrides border colors via require("noctalia").apply_theme()
    autogenerated = false,
})

-- ----------------------------------------------------- 
-- █   ▄▀█ █▄█ █▀█ █ █ ▀█▀ █▀ 
-- █▄▄ █▀█  █  █▄█ █▄█  █  ▄█ 
-- ----------------------------------------------------- 

-- hl.config({
--     dwindle = {
--         pseudotile = true,
--         preserve_split = true,
--     }
-- })

-- ----------------------------------------------------- 
-- █▀▄ ██▀ █ █ █ ▄▀▀ ██▀ █▀ 
-- █▄▀ ██▄ ▀▄▀ █ ▀▄▄ ██▄ ▄█ 
-- ----------------------------------------------------- 

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

-- ----------------------------------------------------- 
-- █▀▄▀█ █ █▀ ▄▀▀ 
-- █ ▀ █ █ ▄█ ▀▄▄ 
-- ----------------------------------------------------- 

hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        force_default_wallpaper = 0,
    }
})
